### ISSUE TITLE
NoSuchMethodError when trying to retrieve card data

### ISSUE THREAD

**Issue by anton8901** [square/in-app-payments-android-quickstart#26]
```
java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;I)V in class Lkotlin/jvm/internal/MutablePropertyReference1Impl; or its super classes (declaration of 'kotlin.jvm.internal.MutablePropertyReference1Impl' appears in /data/app/~~JCfdwcc6t5S0rBZFRM9kwg==/com.greencopper.markfest-NAGFsM4K__HtZuJTbPMc_A==/base.apk!classes4.dex)
        at sqip.internal.BaseCardEntryActivity.<clinit>(Unknown Source:12)
        at sqip.CardEntry.startCardEntryActivity(CardEntry.kt:39)
        at com.greencopper.android.goevent.modules.ordering.provider.square.SquareOrderingPaymentProvider.retrievePaymentData(SquareOrderingPaymentProvider.kt:92)
        at com.greencopper.android.goevent.modules.ordering.OrderingCartFragment.checkout(OrderingCartFragment.kt:140)
        at com.greencopper.android.goevent.modules.ordering.OrderingCartFragment.access$checkout(OrderingCartFragment.kt:37)
        at com.greencopper.android.goevent.modules.ordering.OrderingCartFragment$onCreateView$$inlined$run$lambda$1.onClick(OrderingCartFragment.kt:84)
        at android.view.View.performClick(View.java:7448)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:992)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28305)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

kotlin_version = '1.3.41'

i tried to change to 1.3.61 and 1.3.70 - the result is the same

**Comment by anton8901** [comment]
Downgraded to 1.4.0 and issue disappeared, so 1.5.0 has the issue

**Comment by StephenJosey** [comment]
Can you clarify where you ran into this error? I ran the quickstart as-is, and it worked successfully.

**Comment by anton8901** [comment]
I updated from 1.1.0 to 1.5.0 it has several more issues, but I was able to fix them, but this one is defenetly in library. Downgraded to 1.4.0 and it this issue disappeared. Can you check what changed?

**Comment by pintu236** [comment]
I was also facing same issue working with 1.4.0
